#include <stdbool.h> // booleans, i.e. true and false
#include <stdio.h>   // sprintf() function
#include <stdlib.h>  // srand() and random() functions
#include <time.h>

#include "functions.h" 
#include "ece198.h"

int main(void){

    //part1

    HAL_Init();

    __HAL_RCC_GPIOA_CLK_ENABLE(); // enable port A (for the on-board LED, for example)
    __HAL_RCC_GPIOB_CLK_ENABLE(); // enable port B (for the rotary encoder inputs, for example)
    __HAL_RCC_GPIOC_CLK_ENABLE(); // enable port C (for the on-board blue pushbutton, for example)

    InitializePin(GPIOA, GPIO_PIN_5, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, 0);

    SerialSetup(9600);

    FLAG:

    while (HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_13)){};

    int num_rand = 0;
    num_rand = rand_num();//rand_num();  //get the 2 digit random number

    int rand[2] = {num_rand/10, num_rand%10};   //seperate the 2 digits

    int nu_1 = num_rand/10;
    int nu_2 = num_rand%10;

    //part2

    int *num1;
    num1 = rand_to_morse (nu_1, nu_2);  //transfer random numbers into morse code
    int morse[10] = {0,0,0,0,0,0,0,0,0,0};

    for (int i=0;i<10;i++)
    {
        morse[i] = *(num1+i);
    }

    //It will flash for 0.5s or 1s to represent short or long code. 
    //There will be a 0.1s pause between each character of the codes, and a 1s pause between the two integers. 

    blink_morse (morse);

    //part3

    int answer = rand[0]+ rand[1];  // answer calculated with the two random members generated by the system

    int an_1 = answer/10;
    int an_2 = answer%10;

    int ans_morse[10] = {0,0,0,0,0,0,0,0,0,0};

    int *num2;
    num2 = rand_to_morse (an_1, an_2);   //transfer correct number into morse code

    for (int i=0;i<10;i++)
        {
            ans_morse[i] = *(num2+i);
        }

    //part4

    double time[10] = {0,0,0,0,0,0,0,0,0,0};

    for (int i = 0; i< 10; i++){

        if (time_press() >= 3000){

            goto FLAG;  //if press longer than 3.0 s, then game restart

        }else{

            time[i] = time_press();
        }

    }

    double input[10] = {0,0,0,0,0,0,0,0,0,0};

    for (int i = 0; i< 10; i++){
        //convert time to morse code

        if((time[i] >= 1000 )&&(time[i] <= 3000)){

            input[i] = 1;

        }else if((time[i] < 1000)&& (time[i] > 0)){

            input[i] = 0;

        }
    }

    //part5

    int game_win = 0;

    for (int i=0;i<10;i++)  //check if user input is correct
    {
        if (input[i] == ans_morse[i])
        {
            game_win ++;
        }
    }

    if (game_win == 10){    //check if game win, light blinks

        HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, true);

        return 0;

    }else{  //game restart

        goto FLAG;

    }

}

// This function is called by the HAL once every millisecond
void SysTick_Handler(void)
{
    HAL_IncTick(); // tell HAL that a new tick has happened
    // we can do other things in here too if we need to, but be careful
}
